import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import FireFlyBackground from "./components/background/FireFlyBackground";
import Sound from "./components/Sounds/Sound";
import YepAssistance from "./components/YepAI/YepAssistance";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.variable,
          "bg-background text-foreground font-inter"
        )}
      >
        <YepAssistance zIndex={20} />
        <div className="z-0">
          <FireFlyBackground />
        </div>
        <div className="z-20">
          <Sound />
        </div>
        <div id="my-modal" />
        {children}
      </body>
    </html>
  );
}
